### ISSUE TITLE
Running tests on windows failed with this error.

### ISSUE THREAD

**Issue by iyashpal** [Julien-R44/japa-vscode#1]
![188117294-9ad0f678-99f8-4e30-ab83-7ac7a98f7e0b](https://user-images.githubusercontent.com/19922707/189278066-0f8da7d9-b76b-427b-b320-44768d253dc9.jpg)

**Comment by Julien-R44** [comment]
Oh Powershell ! I use windows too but with Git Bash/ Cygwin. I'll look into it, thanks for the feedback

**Comment by Julien-R44** [comment]
Should be fixed with v0.0.4 that I just published on the marketplace. Can you confirm if it's works for you? 
Thanks !

**Comment by Melchyore** [comment]
@Julien-R44 thank you for the fix, the error is gone, however, when it comes to specific test, it shows "NO TESTS EXECUTED"

![image](https://user-images.githubusercontent.com/6685773/188135789-06d6f3d0-38bf-416a-8088-870bdc0154c3.png)

Note: Runnig the test for the entire file works fine.

**Comment by Julien-R44** [comment]
Oh yeah, it's not directly related but it's definitely a bug. 

You have a "$width" in your test name that disappears (in the last line) because interpolated. I have to escape it. That's a nice edge case 😋 

If you try with a test without `$` it should work

Anyway thanks, I will take care of it!

**Comment by Melchyore** [comment]
Yup, after removing the `$` sign, it works. Thank you!

**Comment by iyashpal** [comment]
> Should be fixed with v0.0.4 that I just published on the marketplace. Can you confirm if it's works for you? Thanks !

Working good. 

Thanks!
