### ISSUE TITLE
Configuring test explorer with @japa/reporter ndjson?

### ISSUE THREAD

**Issue by kenenisa** [Julien-R44/japa-vscode#10]
I see on the `Instructions` section there is 

```TypeScript
import { configure, processCLIArgs, run } from '@japa/runner'
import { assert } from '@japa/assert'
import { ndjson, spec } from '@japa/reporters'

processCLIArgs(process.argv.splice(2))
configure({
  files: ['tests/**/*.spec.js'],
  plugins: [assert()],
  reporters: {
    activated: ['spec'],
    list: [ndJson(), spec()], // 👈 Make sure to include ndjson
  }
})
```

but i can't seem to find `ndjson` nor the package `@japa/reporters`. All i can find is `@japa/spec-reporter` which is used for the spec reporter. I am using japa with adonisjs so i'm configuring japa through `tests/bootstrap.ts`. I can add reporters here

``` TypeScript
/*
|--------------------------------------------------------------------------
| Japa Reporters
|--------------------------------------------------------------------------
|
| Japa reporters displays/saves the progress of tests as they are executed.
| By default, we register the spec reporter to show a detailed report
| of tests on the terminal.
|
*/
export const reporters: Required<Config>['reporters'] = [specReporter()]
```
But i don't know how to add ndjson here. help?

**Comment by Julien-R44** [comment]
Right now you can't do that
To be able to run the tests within the vscode test explorer, you need version 3.0.0 of Japa which is ESM only, and therefore incompatible with Adonis 5

**Comment by Julien-R44** [comment]
Closing the issue, feel free to re-open if needed
