### ISSUE TITLE
Failing to run tests in Workspace environment

### ISSUE THREAD

**Issue by Jule-** [Julien-R44/japa-vscode#12]
Hi!

Firstly, thank you for this useful extension! :slightly_smiling_face: 

I am working with VSCode workspace and then have multiple loaded folders. The issue seems to be related to file path resolution.

The generated command is taking my workspace folder **name** instead of my workspace folder **path** in order to generate the `--files` command option.

For example:
file: `project.code-workspace`
```json
{
  "folders": [
    {
      "name": "My Project",
      "path": "workspace/my-project"
    },
    // ...
  ]
}
```

Knowing that I want to run a test file located at `workspace/my-project/tests/maths.spec.ts`, the generated command line for the test is:
```sh
node --loader ts-node/esm --enable-source-maps bin/test.ts --reporters ndjson --files My Project/tests/maths.spec.ts --groups Maths.add --tests add two numbers
```

Which is showing: `NO TESTS EXECUTED`

While if I run the command manually with correct file path, or without filters, is running my tests correctly.
(btw I am not sure if it is on purpose but `--files ./tests/maths.spec.ts` is failing while `--files tests/maths.spec.ts` is working and I have not seen any mention on how to use this option properly in the doc)

I think this could be a quick fix but I have tried to debug or monkey patch the extension but I am lacking of vscode extension dev knowledge to even log stuff to understand which change I should operate. :sweat_smile: 

If I can help of any kind please let me know.

Cheers!

**Comment by mohitxskull** [comment]
Same problem

**Comment by Jule-** [comment]
@Julien-R44 Hi! Can you help us to fix this? It sounds like a small bug, but I have no experience in VSCode extension development.

Many thanks!

**Comment by Julien-R44** [comment]
Sorry for taking so long. Should be ok with 2.1.4

**Comment by Jule-** [comment]
Hi @Julien-R44, thank you for taking the time to look into it. :pray: Unfortunately, this doesn't solve the issue. I still get the same arguments in the generated command line.

I've made a repro to expose the issue:
https://github.com/Jule-/japa-ext-repro

Obviously, you'll need to open the project with the `workspace.code-workspace` file.

From my understanding, using the Testing tab will not run tests as long as you have a name set on your workspace folder in `workspace.code-workspace` since it generates wrong command lines.

If you have any questions, please let me know.

**Comment by Julien-R44** [comment]
Oh okay I understand, I thought you were using CodeLens to run tests. That's what's been fixed. It seems that the same bug exists when using the Vscode Test Explorer ( Testing Tab ) . Let me check tha

Thanks for the repro

**Comment by Julien-R44** [comment]
Just pushed a new release. Let me know if it works for you with 2.1.5

**Comment by Jule-** [comment]
Wow, that was quick mate! :smiley: This is working like a charm, thanks! :ok_hand: Very much appreciated.

Finally, a decent ESM testing framework that's well integrated with my IDE! :wink:
