### ISSUE TITLE
Test results not reflected in test explorer

### ISSUE THREAD

**Issue by craigharman** [Julien-R44/japa-vscode#15]
I have been using Japa-vscode on a project for the past 6 months and recently I have noticed the the status of the tests is no longer reflecting in the Japa test explorer. 

Things I see:

1. The tests execute and output is provided in "test results" panel
2. The output in "test results" panel is not coloured/formatted (I am not sure if this is expected but I seem to recall it used to be formatted)
3. A test fails in the "test results" panel but the test explorer shows a green "pass" tick.

I haven't added (or use any) additional `reporters` but I also tried adding `ndjson()` to my configuration. This seemed to have no effect. Not sure what else to try.

**Comment by luffynando** [comment]
Yeah its for change in japa 3.x need --reporters=ndjson

Link of change: https://japa.dev/docs/uprade-guide#changes-to-the-reporters-property

Commit of change `reporter` to `reporters`: https://github.com/japa/runner/commit/b18350a38b99f50e52e7be25088659155176121f

Line on extension related:  https://github.com/Julien-R44/japa-vscode/blob/e9469780e9038fccbf3bd359c5c872fe4aee861c/src/tests_runner/ndjson_runner.ts#L202

**Comment by craigharman** [comment]
Can confirm this fixes issue. Thank you!
