### ISSUE TITLE
Error when executing a test that have a `$` in the title

### ISSUE THREAD

**Issue by Julien-R44** [Julien-R44/japa-vscode#2]
@Julien-R44 thank you for the fix, the error is gone, however, when it comes to specific test, it shows "NO TESTS EXECUTED"

![image](https://user-images.githubusercontent.com/6685773/188135789-06d6f3d0-38bf-416a-8088-870bdc0154c3.png)

Note: Runnig the test for the entire file works fine.

_Originally posted by @Melchyore in https://github.com/Julien-R44/japa-vscode/issues/1#issuecomment-1235405599_

**Comment by Julien-R44** [comment]
@Melchyore Should be good ! Published 0.0.5 on the marketplace

**Comment by Melchyore** [comment]
@Julien-R44 Thank you!

![image](https://user-images.githubusercontent.com/6685773/188141288-81351526-fc5a-4ef8-ac8d-b5febd084adf.png)

Still the same problem, as you can see, the word `$with` has been removed with the last fix and replaced with a whitespace.

**Comment by Julien-R44** [comment]
Are you sure you have the latest version? The whitespace was present before. I don't have any problems on my side : 

![image](https://user-images.githubusercontent.com/8337858/188142771-eaf82ba3-ab3f-41c2-a78a-16f453083969.png)

**Comment by Melchyore** [comment]
@Julien-R44 Ok, uninstalled the extension two times, installed it twice, restarting VS Code and didn't work... restarting my laptop, and it worked. Weird but meh, it's Windows... 😂😂

Thank you for the quick fix!
