### ISSUE TITLE
[Suggestion]: Integrate with Test Explorer

### ISSUE THREAD

**Issue by juni0r** [Julien-R44/japa-vscode#7]
Hi!

Wouldn't it be nice to have this integrate with the immensely popular plugin [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer)? There are integrations for every major test framework, so there's plenty of exisiting code to build upon.

Just leaving this here :)

**Comment by Julien-R44** [comment]
Hello, yes it is planned, in fact, it is already a bit the case. You can see all your tests listed in the explorer UI. 
What we don't have is the tests execution. It needs some work but it will happen eventually !

**Comment by juni0r** [comment]
That's great news. Can't wait for it to land eventually!

Yeah, I noticed the test being listed in test explorer and I was in fact a bit confused. I initially thought there was something wrong with my setup since I couldn't run the tests from there. Spent some time checking settings and debug output. Maybe not show them until fully integrated?

Anyways, thanks for all your time invested in making this great plugin. ❤️

**Comment by kenenisa** [comment]
Was looking for this! It would be really awesome if you can integrate it with test explorer UI🔥

**Comment by davidharting** [comment]
Was looking for this as well. My normal workflow is to setup a debug configuration and the test explorer. Then I rely heavily on the "Debug Test at Cursor" command to easy launch the visual debugger for the test I am working on.

**Comment by Julien-R44** [comment]
It took a while, but the integration with Test Explorer is now complete

![](https://github.com/Julien-R44/japa-vscode/assets/8337858/0eba59be-3897-4a70-95a2-06b1195b85b0)

---

Released only as a pre-release for now, to get some feedback. Version 2.0.1, you can switch by clicking on this button in vscode : 

![image](https://github.com/Julien-R44/japa-vscode/assets/8337858/0f012f3d-3383-4ada-b9cc-ee84f20c9c5f)

I'll switch to a normal release once [japa v3 is released](https://github.com/japa/runner/issues/30)

### **Note that you will need Japa version +3.x with the `ndjson` reporter for this feature to work**
Don't hesitate to open issues if you have the opportunity to try it and if you encounter any problems. there will surely be some.

**Comment by davidharting** [comment]
@Julien-R44 You are incredible! Thanks for the amazing work 👏🏻

**Comment by kenenisa** [comment]
Awesome! This is a game changer. Thank you🫡
