### ISSUE TITLE
Can't run a test with the $self placeholder

### ISSUE THREAD

**Issue by Cobs** [Julien-R44/japa-vscode#8]
Hi,

As the title say, I can 't individually run the test below by clicking on the codelense button:
```ts
  test('test with {$self}')
    .with(['a', 'b', 'c'])
    .run((ctx, data) => {
      expect(data).toBe(data)
    })
```
it works fine by running the whole group though.
The console execute the line `cd "/path/to/project && npm run test -- --files "tests/dir/mytest.ts" --tests "test with {\$self}"`
and the output is `NO TESTS EXECUTED`

I tried to tweak a little the command but didn't find a way to launch the test with CLI. As far as i know, it's undocumented on japa, so it could be a Japa bug, I don't know

**Comment by Julien-R44** [comment]
Works fine on my side, I just tried it, check it out:
![image](https://user-images.githubusercontent.com/8337858/236002051-a1940264-b945-4ffd-b767-b134ce921ebb.png)

Care must be taken to ensure that the backslash that escapes the dollar is removed. But should be. Is it the case on your side ?
Also, could you give more information about your setup? OS, Terminal, shell, please?

**Comment by Cobs** [comment]
I use mac os venture 13.3.1, default terminal and shell with a zsh config, but i got the same result with `/bin/bash`

**Comment by Cobs** [comment]
Closing the issue because whatever it is, it's not seems to be related to the extension.
